### PR TITLE
Fix for disabling debug mode for an application.

### PR DESCRIPTION
**Pull request by youngm**
Currently it is not possible to turn off debug between cf and the cloud controller.

Since the api specs are not clear in this area I'm assuming in this patch that cloud controller is functioning correctly and that cf is wrong.  I've submitted a pull request to the cloud controller to test this api. https://github.com/cloudfoundry/cloud_controller_ng/pull/67

This is to fix cf so that it complies with the api cloud controller providing.

### CODE REVIEW

**Comment by jrichard** [comment]
Review and potential merge prioritized in the team's backlog.

**Comment by mariash** [comment]
@youngm Unfortunately we missed a checklist item before merging this commit. All pull request authors must have a Contributor License Agreement (CLA) on-file with us. If you are unable to sign the appropriate CLA ([individual](http://www.cloudfoundry.com/assets/individualcontribution.pdf) or [corporate](http://www.cloudfoundry.com/assets/corpcontribution.pdf)) we may have to revert this commit. Please indicate whether you are interested in doing this and we can give you a few days.

**Comment by youngm** [comment]
I've already signed and submitted a CLA.

**Comment by youngm** [comment]
Just found out my name wasn't showing up in my profile.

Anyway, you should be able to find my CLA under the name Mike Youngstrom

**Comment by youngm** [comment]
Signed the CLA again.

**Pull request merged**
