### PR TITLE
no interactive login with --force flag

### PR DESCRIPTION
**Pull request by hmalphettes**
I am using cf through a shell script.
I noticed that despite using the --force flag there would still be an interactive prompt to login the user. That seems to go against the documentation. Also it is not consistent with cli.rb's method `check_logged_in`

Use case:

```
 cf logout
 cf --force apps
```

should not do an interactive login.

### CODE REVIEW

**Comment by austinbv** [comment]
Sorry it took so long to get to your pull request, but it looks like this has been fixed in master now.  https://github.com/cloudfoundry/cf/blob/master/lib/cf/cli.rb#L76-L83

**Comment by hmalphettes** [comment]
Hi Austin,
I rebased on the latest from master and the new specs I introduced are not passing.
The problem is that when cf rescues an authentication exception it invokes the interactive login directly without checking if the --force flag is on:
https://github.com/cloudfoundry/cf/blob/master/lib/cf/cli.rb#L127

**Comment by austinbv** [comment]
From what I can see in the code this is intended behavior.  I will ask the front end team on monday about having the force flag just error and return you to the prompt.  If that is what they want, I will let you know and fee free to submit another pull request.

**Comment by hmalphettes** [comment]
Hi Austin, let me check against an actual V2: I'd hate to use up my karma credits ;)

**Comment by hmalphettes** [comment]
All working as expected with cf-2.1.0 targeting api.run.pivotal.io
Many thanks for your attention Austin.

**Pull request closed without merging**
