### PR TITLE
remove duplicate directory in config_file_path

### PR DESCRIPTION
**Pull request by omarreiss**
When trying to add custom tunnel clients, I came accross two errors:

1) I found out that the file that cf uses to check for custom clients is not `clients.yml` but `tunnel-clients.yml`. So I updated the readme accordingly. Can be verified [here](https://github.com/cloudfoundry/cf/blob/master/lib/tunnel/plugin.rb#L6)

2) I found a duplication in the `config_file_path` method. `CF::CONFIG_DIR` returns `.cf` as can be verified [here](https://github.com/cloudfoundry/cf/blob/master/lib/cf/constants.rb#L2). I removed the hardcoded `.cf` from the path.

### CODE REVIEW

**Comment by omarreiss** [comment]
I belong to the organization Innovation Factory, for which a CLA was signed already

**Comment by ryantang** [comment]
@omarreiss — Thanks for the pull request.  

1) We searched for the Innovation Factory CLA but weren't able to find it.  Can you resend it to contributors@cloudfoundry.org?  That's a group email that would be properly archived.

2) Thanks for finding the CONFIG_DIR bug.  Can you write a test that would expose this bug and demonstrate that your change fixed it?

@AndreasMaier / @ryantang

**Comment by omarreiss** [comment]
@ryantang I will send the CLA to contributors@cloudfoundry.org later today.

**Comment by omarreiss** [comment]
CLA sent. You might have received two e-mails from me. I forgot to add the attachment the first time. :smile:

**Comment by jbayer** [comment]
@omarreiss we have the CLA on-file now. Thanks for sending it. /cc @ryantang

**Pull request merged**
