### PR TITLE
Display next command on new line

### PR DESCRIPTION
**Pull request by drnic**
This allows for triple-click to select the whole line for easy copy/paste
into terminal.

Usage:

```
$ bundle exec bin/cf.dev create-space
Name> test5

Creating space test5... OK
Adding you as a manager... OK
Adding you as a developer... OK
Space created!

cf switch-space test5    # targets new space
```

### CODE REVIEW

**Comment by dmrschmidt** [comment]
Isn't the old `Use 'cf switch-space #{new_space.name}' to target it` more descriptive to new users?

**Comment by drnic** [comment]
The changes makes the output like "rake -T" and display the command in a format that can be very easily copy and pasted. 

Currently, you need to carefully select the text before copy & paste. Or you need to correctly type it out.

**Comment by dmrschmidt** [comment]
True. I will bring this up for a quick discussion in the team. We can't merge the Pull Request right away as it is however since it broke our integration specs.

**Comment by drnic** [comment]
Ooh sorry about the tests!

**Pull request merged**
